export type TourStepKey =
  | 'welcome'
  | 'homeNewProject'
  | 'newProjectName'
  | 'newProjectCustomDb'
  | 'newProjectCreate'
  | 'projectSdkTokenOverview'
  | 'projectSdkTokenTabInfo'
  | 'projectImportDataTab'
  | 'projectImportOverview'
  | 'projectImportRadio'
  | 'projectImportIngest'
  | 'recordTableOverview'
  | 'recordTableSearchInput'
  | 'recordTableViewMode'
