export type TourStepKey =
  | 'welcome'
  | 'projectSdkTokenOverview'
  | 'projectSdkTokenTabInfo'
  | 'projectImportDataTab'
  | 'projectImportOverview'
  | 'projectImportRadio'
  | 'projectImportIngest'
  | 'projectIndexSuggestions'
  | 'projectIndexCreate'
  | 'projectRelationshipAnalyze'
  | 'projectRelationshipApprove'
  | 'recordGraphView'
  | 'recordRawApiMode'
  | 'rawApiSelectQuery'
  | 'rawApiRunQuery'
  | 'rawApiResults'
  | 'projectGettingStartedFinish'
