#!/usr/bin/env bash
#
# RushDB self-hosted installer.
#
# Brings up the full RushDB stack (RushDB + Neo4j + Postgres) with one command,
# generating strong secrets into a local .env so nothing ships with default
# passwords.
#
# Run inside a clone:
#   ./deploy/install.sh
#
# Or standalone (downloads the compose file into ./rushdb):
#   curl -fsSL https://raw.githubusercontent.com/rush-db/rushdb/main/deploy/install.sh | bash
#
set -euo pipefail

RAW_BASE="https://raw.githubusercontent.com/rush-db/rushdb/main/deploy/templates/docker-compose"
COMPOSE_FILE="compose.full.yaml"
ENV_FILE=".env"
PORT="${RUSHDB_PORT:-3000}"

c_green=$'\033[0;32m'; c_yellow=$'\033[0;33m'; c_red=$'\033[0;31m'; c_dim=$'\033[2m'; c_reset=$'\033[0m'
info()  { printf '%s==>%s %s\n' "$c_green" "$c_reset" "$*"; }
warn()  { printf '%s!  %s%s\n' "$c_yellow" "$*" "$c_reset"; }
die()   { printf '%sx  %s%s\n' "$c_red" "$*" "$c_reset" >&2; exit 1; }

# --- preflight ---------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "Docker is required. Install it: https://docs.docker.com/get-docker/"
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "Docker Compose v2 is required (docker compose)."
fi
docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker and retry."

# --- locate or fetch the compose file ----------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 && pwd)"
if [ -f "$SCRIPT_DIR/templates/docker-compose/$COMPOSE_FILE" ]; then
  # Running from inside the repo: work in the template dir.
  WORKDIR="$SCRIPT_DIR/templates/docker-compose"
elif [ -f "./$COMPOSE_FILE" ]; then
  WORKDIR="$(pwd)"
else
  WORKDIR="$(pwd)/rushdb"
  info "Downloading RushDB compose template into $WORKDIR"
  mkdir -p "$WORKDIR"
  curl -fsSL "$RAW_BASE/$COMPOSE_FILE" -o "$WORKDIR/$COMPOSE_FILE" || die "Failed to download $COMPOSE_FILE"
fi
cd "$WORKDIR"

# --- secret generation -------------------------------------------------------
gen_hex() { # $1 = bytes -> 2*$1 hex chars
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"
  else head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}
gen_pass() { # url-safe password, ~24 chars
  if command -v openssl >/dev/null 2>&1; then openssl rand -base64 18 | tr -d '/+=' | cut -c1-24
  else head -c 18 /dev/urandom | od -An -tx1 | tr -d ' \n' | cut -c1-24; fi
}

if [ -f "$ENV_FILE" ]; then
  warn "$ENV_FILE already exists — keeping your secrets, not regenerating."
  ADMIN_PW="$(grep -E '^RUSHDB_PASSWORD=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)"
else
  info "Generating $ENV_FILE with fresh secrets"
  ADMIN_PW="$(gen_pass)"
  AES_KEY="$(gen_hex 16)"        # 32 hex chars
  NEO4J_PW="$(gen_pass)"
  PG_PW="$(gen_pass)"
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file private.
RUSHDB_PORT=$PORT
RUSHDB_LOGIN=admin
RUSHDB_PASSWORD=$ADMIN_PW
RUSHDB_AES_256_ENCRYPTION_KEY=$AES_KEY
RUSHDB_DASHBOARD_URL=http://localhost:$PORT
RUSHDB_BASE_URL=http://localhost:$PORT

NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=$NEO4J_PW

POSTGRES_DB=rushdb
POSTGRES_USER=rushdb
POSTGRES_PASSWORD=$PG_PW
EOF
  chmod 600 "$ENV_FILE"
fi

# --- launch ------------------------------------------------------------------
info "Pulling images and starting the stack (Neo4j first boot can take ~30s)"
$COMPOSE -f "$COMPOSE_FILE" up -d

printf '\n%s==>%s RushDB is starting.\n' "$c_green" "$c_reset"
printf '   Dashboard:  %shttp://localhost:%s%s\n' "$c_green" "$PORT" "$c_reset"
printf '   Login:      admin\n'
printf '   Password:   %s\n' "${ADMIN_PW:-see $WORKDIR/$ENV_FILE}"
printf '   %sSecrets saved to %s/%s (chmod 600).%s\n\n' "$c_dim" "$WORKDIR" "$ENV_FILE" "$c_reset"
printf '   Follow logs:  %s -f %s logs -f rushdb\n' "$COMPOSE" "$COMPOSE_FILE"
printf '   Stop:         %s -f %s down\n\n' "$COMPOSE" "$COMPOSE_FILE"
