version: "3.8"
services:
    backend:
        container_name: backend
        build:
            context: ../..
            target: development
            dockerfile: platform/core/Dockerfile
        command: npm run start:debug
        volumes:
            - ./:/app
        depends_on:
            neo4j:
                condition: service_healthy
        environment:
            - NODE_ENV=development
            - RUSHDB_DASHBOARD_URL=${RUSHDB_DASHBOARD_URL}
            - NEO4J_URL=${NEO4J_URL}
            - NEO4J_USERNAME=${NEO4J_USERNAME}
            - NEO4J_PASSWORD=${NEO4J_PASSWORD}
            - RUSHDB_PORT=${RUSHDB_PORT}
            - RATE_LIMITER_REQUESTS_LIMIT=${RATE_LIMITER_REQUESTS_LIMIT}
            - RATE_LIMITER_TTL=${RATE_LIMITER_TTL}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_SECRET=${GOOGLE_SECRET}
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_SECRET=${GITHUB_SECRET}
            - GITHUB_REDIRECT_URL=${GITHUB_REDIRECT_URL}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_USER=${MAIL_USER}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAIL_FROM=${MAIL_FROM}
            - SERVICE_CAPTCHA_KEY=${SERVICE_CAPTCHA_KEY}
            - RUSHDB_LOGIN=${RUSHDB_LOGIN}
            - RUSHDB_PASSWORD=${RUSHDB_PASSWORD}
            - RUSHDB_AES_256_ENCRYPTION_KEY=${RUSHDB_AES_256_ENCRYPTION_KEY}

            - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
            - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

            - RUSHDB_ALLOWED_LOGINS=${RUSHDB_ALLOWED_LOGINS}
            - RUSHDB_SELF_HOSTED=${RUSHDB_SELF_HOSTED}
        ports:
            - ${RUSHDB_PORT}:${RUSHDB_PORT}
        networks:
            - rushdb
        restart: always
        labels:
            org.label-schema.group: "app"

    neo4j:
        image: neo4j:5.25.1
        healthcheck:
            test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
            interval: 5s
            retries: 30
            start_period: 10s
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_server_directories_run=/run
            - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
            - USERNAME=${NEO4J_USERNAME}
            - PASSWORD=${NEO4J_PASSWORD}
        networks:
            - rushdb
        volumes:
            - ./neo4j/plugins:/plugins
        labels:
            org.label-schema.group: "app"

    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile.dev
        depends_on:
            - backend
        ports:
            - "80:80"
        restart: always
        networks:
            - rushdb
        labels:
            org.label-schema.group: "app"

networks:
    rushdb:
        driver: bridge

volumes:
    mg_lib:
    mg_log:
    mg_etc:
