version: "3.8"
services:
    neo4j:
        image: neo4j:5.25.1
        healthcheck:
            test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
            interval: 5s
            retries: 30
            start_period: 10s
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_server_directories_run=/run
            - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
            - USERNAME=${NEO4J_USERNAME}
            - PASSWORD=${NEO4J_PASSWORD}
        networks:
            - rushdb-network
        volumes:
            - ./neo4j/plugins:/plugins
        labels:
            org.label-schema.group: "app"

networks:
    rushdb-network:
        driver: bridge
