// Generated by migrate-slugs.mjs — old explicit slugs redirected to their
// path-derived URLs after the docs URL scheme moved to mirror the on-disk layout.
const slugMigrationRedirects: Array<{ from: string; to: string }> = [
  {
    "from": "/deploy/config-env-variables",
    "to": "/deploy/configuration/environment-variables"
  },
  {
    "from": "/deploy/get-api-key",
    "to": "/deploy/configuration/get-api-key"
  },
  {
    "from": "/deploy/config-index",
    "to": "/deploy/configuration"
  },
  {
    "from": "/deploy/config-security",
    "to": "/deploy/configuration/security"
  },
  {
    "from": "/deploy/connect-aura",
    "to": "/deploy/guides/connect-aura"
  },
  {
    "from": "/deploy/mcp-operator-quickstart",
    "to": "/deploy/guides/mcp-operator-quickstart"
  },
  {
    "from": "/deploy/self-hosted-project-setup",
    "to": "/deploy/guides/self-hosted-project-setup"
  },
  {
    "from": "/deploy/infra-index",
    "to": "/deploy/infrastructure"
  },
  {
    "from": "/deploy/infra-neo4j",
    "to": "/deploy/infrastructure/neo4j-and-aura"
  },
  {
    "from": "/deploy/infra-database",
    "to": "/deploy/infrastructure/postgresql-sqlite"
  },
  {
    "from": "/deploy/infra-platform",
    "to": "/deploy/infrastructure/rushdb-platform"
  },
  {
    "from": "/deploy/local-docker",
    "to": "/deploy/local-hosting/docker"
  },
  {
    "from": "/deploy/local-source",
    "to": "/deploy/local-hosting/from-source"
  },
  {
    "from": "/deploy/local-helm",
    "to": "/deploy/local-hosting/helm"
  },
  {
    "from": "/deploy/local-index",
    "to": "/deploy/local-hosting"
  },
  {
    "from": "/deploy/remote-cloud-providers",
    "to": "/deploy/remote-hosting/aws-gcp-azure"
  },
  {
    "from": "/deploy/remote-digital-ocean",
    "to": "/deploy/remote-hosting/digital-ocean"
  },
  {
    "from": "/deploy/remote-index",
    "to": "/deploy/remote-hosting"
  },
  {
    "from": "/deploy/remote-prerequisites",
    "to": "/deploy/remote-hosting/prerequisites"
  },
  {
    "from": "/deploy/docker-remote",
    "to": "/deploy/remote-hosting/self-hosting-rushdb"
  },
  {
    "from": "/build/agent-memory",
    "to": "/learn/agent-memory"
  },
  {
    "from": "/build/agent-memory/quickstart",
    "to": "/learn/agent-memory/quickstart"
  },
  {
    "from": "/build/agent-memory/schema-self-awareness",
    "to": "/learn/agent-memory/schema-self-awareness"
  },
  {
    "from": "/build/schema/discover-your-schema",
    "to": "/learn/records-and-queries/discover-your-schema"
  },
  {
    "from": "/build/data/export-data",
    "to": "/learn/records-and-queries/export-data"
  },
  {
    "from": "/build/data/find-and-query",
    "to": "/learn/records-and-queries/find-and-query"
  },
  {
    "from": "/build/data/import-data",
    "to": "/learn/records-and-queries/import-data"
  },
  {
    "from": "/build/data",
    "to": "/learn/records-and-queries"
  },
  {
    "from": "/build/data/labeled-meta-property-graph",
    "to": "/learn/records-and-queries/labeled-meta-property-graph"
  },
  {
    "from": "/build/schema/labels-and-properties",
    "to": "/learn/records-and-queries/labels-and-properties"
  },
  {
    "from": "/build/raw-queries",
    "to": "/learn/records-and-queries/raw-queries"
  },
  {
    "from": "/build/data/store-records",
    "to": "/learn/records-and-queries/store-records"
  },
  {
    "from": "/build/reliability/transactions",
    "to": "/learn/records-and-queries/transactions"
  },
  {
    "from": "/reference/mcp",
    "to": "/learn/reference/mcp"
  },
  {
    "from": "/reference/mcp/tools",
    "to": "/learn/reference/mcp/tools"
  },
  {
    "from": "/reference/python/RushDB",
    "to": "/learn/reference/python/RushDB"
  },
  {
    "from": "/reference/python/SearchQuery",
    "to": "/learn/reference/python/SearchQuery"
  },
  {
    "from": "/reference/python",
    "to": "/learn/reference/python"
  },
  {
    "from": "/reference/python/record",
    "to": "/learn/reference/python/record"
  },
  {
    "from": "/reference/python/relationship-patterns",
    "to": "/learn/reference/python/relationship-patterns"
  },
  {
    "from": "/reference/python/search-result",
    "to": "/learn/reference/python/search-result"
  },
  {
    "from": "/reference/python/transaction",
    "to": "/learn/reference/python/transaction"
  },
  {
    "from": "/rest-api/ai/advanced-indexing",
    "to": "/learn/reference/rest-api/ai-and-vectors/advanced-indexing"
  },
  {
    "from": "/rest-api/ai/indexing",
    "to": "/learn/reference/rest-api/ai-and-vectors/indexing"
  },
  {
    "from": "/rest-api/ai/overview",
    "to": "/learn/reference/rest-api/ai-and-vectors/overview"
  },
  {
    "from": "/rest-api/ai/search",
    "to": "/learn/reference/rest-api/ai-and-vectors/search"
  },
  {
    "from": "/rest-api/ai/write-with-vectors",
    "to": "/learn/reference/rest-api/ai-and-vectors/write-with-vectors"
  },
  {
    "from": "/rest-api/introduction",
    "to": "/learn/reference/rest-api/introduction"
  },
  {
    "from": "/rest-api/labels",
    "to": "/learn/reference/rest-api/labels"
  },
  {
    "from": "/rest-api/properties",
    "to": "/learn/reference/rest-api/properties"
  },
  {
    "from": "/rest-api/raw-queries",
    "to": "/learn/reference/rest-api/raw-queries"
  },
  {
    "from": "/rest-api/records/create-records",
    "to": "/learn/reference/rest-api/records/create-records"
  },
  {
    "from": "/rest-api/records/delete-records",
    "to": "/learn/reference/rest-api/records/delete-records"
  },
  {
    "from": "/rest-api/records/export-data",
    "to": "/learn/reference/rest-api/records/export-data"
  },
  {
    "from": "/rest-api/records/get-records",
    "to": "/learn/reference/rest-api/records/get-records"
  },
  {
    "from": "/rest-api/records/import-data",
    "to": "/learn/reference/rest-api/records/import-data"
  },
  {
    "from": "/rest-api/records/update-records",
    "to": "/learn/reference/rest-api/records/update-records"
  },
  {
    "from": "/rest-api/relationships",
    "to": "/learn/reference/rest-api/relationships"
  },
  {
    "from": "/rest-api/transactions",
    "to": "/learn/reference/rest-api/transactions"
  },
  {
    "from": "/reference/typescript/DBRecord",
    "to": "/learn/reference/typescript/DBRecord"
  },
  {
    "from": "/reference/typescript/DBRecordInstance",
    "to": "/learn/reference/typescript/DBRecordInstance"
  },
  {
    "from": "/reference/typescript/DBRecordTarget",
    "to": "/learn/reference/typescript/DBRecordTarget"
  },
  {
    "from": "/reference/typescript/DBRecordsArrayInstance",
    "to": "/learn/reference/typescript/DBRecordsArrayInstance"
  },
  {
    "from": "/reference/typescript/Model",
    "to": "/learn/reference/typescript/Model"
  },
  {
    "from": "/reference/typescript/RelationTarget",
    "to": "/learn/reference/typescript/RelationTarget"
  },
  {
    "from": "/reference/typescript/RushDB",
    "to": "/learn/reference/typescript/RushDB"
  },
  {
    "from": "/reference/typescript/SearchQuery",
    "to": "/learn/reference/typescript/SearchQuery"
  },
  {
    "from": "/reference/typescript/Transaction",
    "to": "/learn/reference/typescript/Transaction"
  },
  {
    "from": "/reference/typescript",
    "to": "/learn/reference/typescript"
  },
  {
    "from": "/reference/typescript/relationship-patterns",
    "to": "/learn/reference/typescript/relationship-patterns"
  },
  {
    "from": "/build/graph/bulk-relationships",
    "to": "/learn/relationships/bulk-relationships"
  },
  {
    "from": "/build/graph/connect-records",
    "to": "/learn/relationships/connect-records"
  },
  {
    "from": "/build/graph",
    "to": "/learn/relationships"
  },
  {
    "from": "/build/graph/relationship-properties",
    "to": "/learn/relationships/relationship-properties"
  },
  {
    "from": "/build/graph/suggested-patterns",
    "to": "/learn/relationships/suggested-patterns"
  },
  {
    "from": "/reference/group-by",
    "to": "/learn/search-query/group-by"
  },
  {
    "from": "/reference/pagination-order",
    "to": "/learn/search-query/pagination-order"
  },
  {
    "from": "/reference/search-labels",
    "to": "/learn/search-query/search-labels"
  },
  {
    "from": "/reference/search-query",
    "to": "/learn/search-query"
  },
  {
    "from": "/reference/select-expressions",
    "to": "/learn/search-query/select-expressions"
  },
  {
    "from": "/reference/where-operators",
    "to": "/learn/search-query/where-operators"
  },
  {
    "from": "/build/ai-search/bring-your-own-vectors",
    "to": "/learn/semantic-search/bring-your-own-vectors"
  },
  {
    "from": "/build/ai-search/manage-indexes",
    "to": "/learn/semantic-search/manage-indexes"
  },
  {
    "from": "/build/ai-search/semantic-search",
    "to": "/learn/semantic-search"
  },
  {
    "from": "/build/ai-search/write-with-vectors",
    "to": "/learn/semantic-search/write-with-vectors"
  },
  {
    "from": "/tutorials/agent-safe-query-planning",
    "to": "/learn/tutorials/agent-memory/agent-safe-query-planning"
  },
  {
    "from": "/tutorials/agent-skills-with-openclaw",
    "to": "/learn/tutorials/agent-memory/agent-skills-with-openclaw"
  },
  {
    "from": "/tutorials/building-team-memory",
    "to": "/learn/tutorials/agent-memory/building-team-memory"
  },
  {
    "from": "/tutorials/episodic-memory",
    "to": "/learn/tutorials/agent-memory/episodic-memory"
  },
  {
    "from": "/tutorials/memory-layer",
    "to": "/learn/tutorials/agent-memory/memory-layer"
  },
  {
    "from": "/tutorials/research-knowledge-graph",
    "to": "/learn/tutorials/agent-memory/research-knowledge-graph"
  },
  {
    "from": "/tutorials/ai-semantic-search",
    "to": "/learn/tutorials/ai-and-rag/ai-semantic-search"
  },
  {
    "from": "/tutorials/byov-external-embeddings",
    "to": "/learn/tutorials/ai-and-rag/byov-external-embeddings"
  },
  {
    "from": "/tutorials/byov-when-and-why",
    "to": "/learn/tutorials/ai-and-rag/byov-when-and-why"
  },
  {
    "from": "/tutorials/explainable-results",
    "to": "/learn/tutorials/ai-and-rag/explainable-results"
  },
  {
    "from": "/tutorials/graphrag",
    "to": "/learn/tutorials/ai-and-rag/graphrag"
  },
  {
    "from": "/tutorials/hybrid-retrieval",
    "to": "/learn/tutorials/ai-and-rag/hybrid-retrieval"
  },
  {
    "from": "/tutorials/rag-evaluation",
    "to": "/learn/tutorials/ai-and-rag/rag-evaluation"
  },
  {
    "from": "/tutorials/rag-multi-source",
    "to": "/learn/tutorials/ai-and-rag/rag-multi-source"
  },
  {
    "from": "/tutorials/rag-pipeline",
    "to": "/learn/tutorials/ai-and-rag/rag-pipeline"
  },
  {
    "from": "/tutorials/rag-reranking",
    "to": "/learn/tutorials/ai-and-rag/rag-reranking"
  },
  {
    "from": "/tutorials/semantic-search-multitenant",
    "to": "/learn/tutorials/ai-and-rag/semantic-search-multitenant"
  },
  {
    "from": "/tutorials/choosing-relationship-types",
    "to": "/learn/tutorials/graph-modeling/choosing-relationship-types"
  },
  {
    "from": "/tutorials/customer-360",
    "to": "/learn/tutorials/graph-modeling/customer-360"
  },
  {
    "from": "/tutorials/data-lineage",
    "to": "/learn/tutorials/graph-modeling/data-lineage"
  },
  {
    "from": "/tutorials/modeling-hierarchies",
    "to": "/learn/tutorials/graph-modeling/modeling-hierarchies"
  },
  {
    "from": "/tutorials/temporal-graphs",
    "to": "/learn/tutorials/graph-modeling/temporal-graphs"
  },
  {
    "from": "/tutorials/thinking-in-graphs",
    "to": "/learn/tutorials/graph-modeling/thinking-in-graphs"
  },
  {
    "from": "/tutorials/versioning-records",
    "to": "/learn/tutorials/graph-modeling/versioning-records"
  },
  {
    "from": "/tutorials",
    "to": "/learn/tutorials"
  },
  {
    "from": "/tutorials/discovery-queries",
    "to": "/learn/tutorials/search-and-queries/discovery-queries"
  },
  {
    "from": "/tutorials/query-optimization",
    "to": "/learn/tutorials/search-and-queries/query-optimization"
  },
  {
    "from": "/tutorials/reusable-search-query",
    "to": "/learn/tutorials/search-and-queries/reusable-search-query"
  },
  {
    "from": "/tutorials/search-ux-patterns",
    "to": "/learn/tutorials/search-and-queries/search-ux-patterns"
  },
  {
    "from": "/tutorials/searchquery-advanced-patterns",
    "to": "/learn/tutorials/search-and-queries/searchquery-advanced-patterns"
  },
  {
    "from": "/tutorials/testing-searchquery",
    "to": "/learn/tutorials/search-and-queries/testing-searchquery"
  },
  {
    "from": "/tutorials/audit-trails",
    "to": "/learn/tutorials/use-cases/audit-trails"
  },
  {
    "from": "/tutorials/byoc-vs-managed",
    "to": "/learn/tutorials/use-cases/byoc-vs-managed"
  },
  {
    "from": "/tutorials/compliance-retention",
    "to": "/learn/tutorials/use-cases/compliance-retention"
  },
  {
    "from": "/tutorials/incident-response",
    "to": "/learn/tutorials/use-cases/incident-response"
  },
  {
    "from": "/tutorials/is-rushdb-right-for-me",
    "to": "/learn/tutorials/use-cases/is-rushdb-right-for-me"
  },
  {
    "from": "/tutorials/supply-chain-traceability",
    "to": "/learn/tutorials/use-cases/supply-chain-traceability"
  },
  {
    "from": "/tutorials/event-driven-ingestion",
    "to": "/learn/tutorials/working-with-data/event-driven-ingestion"
  },
  {
    "from": "/tutorials/graph-backed-api",
    "to": "/learn/tutorials/working-with-data/graph-backed-api"
  },
  {
    "from": "/tutorials/importing-data",
    "to": "/learn/tutorials/working-with-data/importing-data"
  },
  {
    "from": "/tutorials/importing-from-mongodb",
    "to": "/learn/tutorials/working-with-data/importing-from-mongodb"
  },
  {
    "from": "/tutorials/third-party-webhook-ingestion",
    "to": "/learn/tutorials/working-with-data/third-party-webhook-ingestion"
  },
  {
    "from": "/cloud/billing-model",
    "to": "/rushdb-cloud/billing-model"
  },
  {
    "from": "/cloud",
    "to": "/rushdb-cloud"
  },
  {
    "from": "/cloud/knowledge-units",
    "to": "/rushdb-cloud/knowledge-units"
  },
  {
    "from": "/cloud/licensing-and-services",
    "to": "/rushdb-cloud/licensing-and-services"
  },
  {
    "from": "/cloud/project-isolation",
    "to": "/rushdb-cloud/project-isolation"
  }
]

export default slugMigrationRedirects
