import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  restApi: [{ type: 'autogenerated', dirName: 'rest-api' }],
  pythonSdk: [{ type: 'autogenerated', dirName: 'python-sdk' }],
  typescriptSdk: [{ type: 'autogenerated', dirName: 'typescript-sdk' }],
  mcpServer: [{ type: 'autogenerated', dirName: 'mcp-server' }],
  tutorials: [{ type: 'autogenerated', dirName: 'tutorials' }],
  docs: [
    {
      type: 'link',
      label: 'Python SDK',
      href: '/python-sdk/introduction',
      className: 'python-sdk sdk-link'
    },
    {
      type: 'link',
      label: 'TypeScript SDK',
      href: '/typescript-sdk/introduction',
      className: 'typescript-sdk sdk-link'
    },
    {
      type: 'link',
      label: 'REST API',
      href: '/rest-api/introduction',
      className: 'rest-api sdk-link'
    },
    {
      type: 'link',
      label: 'MCP Server',
      href: '/mcp-server/introduction',
      className: 'mcp-server sdk-link'
    },
    {
      type: 'link',
      label: 'Tutorials',
      href: '/tutorials',
      className: 'tutorials-link sdk-link'
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['index', 'get-started/get-api-key', 'get-started/quick-tutorial']
    },
    'concepts/agent-memory-model',
    'concepts/ontology-schema-discovery',
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'concepts/index',
        'concepts/records',
        'concepts/data-ingestion',
        'concepts/labels',
        'concepts/properties',
        'concepts/relationships',
        'concepts/semantic-search',
        'concepts/bring-your-own-vectors',
        'concepts/storage',
        'concepts/transactions',
        {
          label: 'Search',
          collapsible: true,
          collapsed: true,
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'concepts/search'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Pricing & Billing',
      collapsed: false,
      items: ['concepts/knowledge-units', 'concepts/billing-model']
    }
  ]
}

export default sidebars
