import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  restApi: [{ type: 'autogenerated', dirName: 'rest-api' }],
  pythonSdk: [{ type: 'autogenerated', dirName: 'python-sdk' }],
  typescriptSdk: [{ type: 'autogenerated', dirName: 'typescript-sdk' }],
  docs: [
    {
      type: 'link',
      label: 'Python SDK',
      href: '/python-sdk/introduction',
      className: 'python-sdk sdk-link'
    },
    {
      type: 'link',
      label: 'TypeScript SDK',
      href: '/typescript-sdk/introduction',
      className: 'typescript-sdk sdk-link'
    },
    {
      type: 'link',
      label: 'REST API',
      href: '/rest-api/introduction',
      className: 'rest-api sdk-link'
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['index', 'get-started/get-api-key', 'get-started/quick-tutorial']
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'concepts/storage',
        'concepts/records',
        'concepts/labels',
        'concepts/properties',
        'concepts/relationships',
        'concepts/transactions',
        {
          label: 'Search',
          collapsible: true,
          collapsed: true,
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'concepts/search'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        'tutorials/configuring-dashboard',
        'tutorials/deployment',
        'tutorials/local-setup',
        'tutorials/reusable-search-query'
      ]
    }
  ]
}

export default sidebars
