name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.version }}
      has_tag: ${{ steps.check-tag.outputs.has_tag }}
      is_version_bump: ${{ steps.check-commit.outputs.is_version_bump }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install

      - name: Build SDK
        run: pnpm --filter ./packages/javascript-sdk... build

      - name: Setup .npmrc
        run: |
          cat << EOF > ~/.npmrc
          registry=https://registry.npmjs.org/
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          access=public
          always-auth=true
          EOF

      - name: Get Package Version
        id: package-version
        run: |
          VERSION=$(jq -r '.version' ./packages/javascript-sdk/package.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT    

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm release --filter ./packages/javascript-sdk...
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check Tag Creation
        id: check-tag
        run: |
          if git rev-parse "@rushdb/javascript-sdk@${{ steps.package-version.outputs.version }}" >/dev/null 2>&1; then
            echo "has_tag=true" >> $GITHUB_OUTPUT
          else
            echo "has_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Check Commit Type
        id: check-commit
        run: |
          if git log -1 --pretty=%B | grep -q "chore(release): version packages"; then
            echo "is_version_bump=true" >> $GITHUB_OUTPUT
          else
            echo "is_version_bump=false" >> $GITHUB_OUTPUT
          fi    

  docker:
    needs: release
    if: needs.release.outputs.is_version_bump == 'true'
    runs-on: ubuntu-latest

    steps:
      - run: echo '${{ toJSON(needs.release.outputs) }}'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: platform/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            rushdb/platform:latest
            rushdb/platform:${{ needs.release.outputs.version }}